version: '3.8'

services:
     
  redis-master:
    image: redislabs/redisearch:latest
    container_name: redis-master
    restart: on-failure
    hostname: redis
    command: redis-server --loadmodule /usr/lib/redis/modules/redisearch.so --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - "./.data:/data"
 
  redis-slave:
    image: redislabs/redisearch:latest
    command: redis-server --slaveof redis-master 6379 --loadmodule /usr/lib/redis/modules/redisearch.so --appendonly yes
    links:
      - redis-master
    volumes:
      - "./.data:/data"
  redis-slave2:
    image: redislabs/redisearch:latest
    command: redis-server --slaveof redis-master 6379 --loadmodule /usr/lib/redis/modules/redisearch.so --appendonly yes
    links:
      - redis-master
    volumes:
      - "./.data:/data"
     
  # Instance 1
  redis-sentinel:
    build: 
      context: ./redis-sentinel
    ports:
      - 26379:26379
    links:
      - redis-master
 
  # Instance 2
  redis-sentinel2:
    build: 
      context: ./redis-sentinel
    ports:
      - 26381:26379
    links:
      - redis-master
 
  # Instance 3
  redis-sentinel3:
    build: 
      context: ./redis-sentinel
    ports:
      - 26380:26379
    links:
      - redis-master
    